apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-app
  name: web-app
  namespace: _{_NAMESPACE_}_
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - image: _{_IMAGE_}_
        name: web-app
        ports:
        - containerPort: 5000
        env:
        - name: DB_NAME
          value: "webapp"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: DB_HOST
          value: "postgres-service"  # Adjust if needed
        - name: DB_PORT
          value: "5432"

---
apiVersion: v1
kind: Service
metadata:
  name: web-app
  namespace: _{_NAMESPACE_}_
spec:
  type: NodePort  # Change to NodePort
  selector:
    app: web-app
  ports:
    - port: 80         # The port that will be exposed
      targetPort: 5000 # The port on the container
      nodePort: 30000   # Specify the NodePort if you want a specific port; otherwise, one will be assigned automatically

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: _{_NAMESPACE_}_
spec:
  type: ClusterIP  # Typically, PostgreSQL doesn't need to be exposed externally
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres  # Ensure you have a Deployment or StatefulSet with this label for the PostgreSQL pod
