apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-app
  name: web-app
  namespace: _{_NAMESPACE_}_
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - image: _{_IMAGE_}_
        name: web-app
        ports:
        - containerPort: 5000
        env:
        - name: DB_NAME
          value: "webapp"
        - name: DB_USER
          value: "webapp"  # Hard-coded user
        - name: DB_PASSWORD
          value: "1234"  # Hard-coded password
        - name: DB_HOST
          value: "20.109.16.207"  # Replace with your PostgreSQL host, if needed
        - name: DB_PORT
          value: "5432"

---
apiVersion: v1
kind: Service
metadata:
  name: web-app
  namespace: _{_NAMESPACE_}_
spec:
  type: NodePort  # Change to NodePort
  selector:
    app: web-app
  ports:
    - port: 80         # The port that will be exposed
      targetPort: 5000 # The port on the container
      nodePort: 30000   # Specify the NodePort if you want a specific port; otherwise, one will be assigned automatically
