name: web-app
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    
    steps:
    # Runs a single command using the runners shell
    - name: check node
      run: kubectl get node

    - name: docker login
      run: docker login --username="${{ secrets.DOCKERHUB_USERNAME }}" --password="${{ secrets.DOCKERHUB_TOKEN }}"
      
    - name: docker logout
      run: docker logout || true
