name: web-app

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    # Step 1: Check Kubernetes nodes using kubectl
    - name: Check Kubernetes Nodes
      run: |
        kubectl get node

    # Step 2: Docker Login
    - name: Docker Login
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username="${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
    
    # Step 3: Docker Logout
    - name: Docker Logout
      run: |
        docker logout || true

    # Step 4: Postgres Login and Execute psql Commands
    - name: Postgres Login and Execute psql Commands
      run: |
        PGPASSWORD="${{ secrets.POSTGRES_PASSWORD }}" psql --host="${{ secrets.POSTGRES_HOST }}" --port="${{ secrets.POSTGRES_PORT }}" --username="${{ secrets.POSTGRES_USER }}" --dbname="${{ secrets.POSTGRES_DB }}" <<EOF
        \dt
        \q
        EOF
